### ISSUE TITLE
Show error when filtering enum invalid values

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/django-binder#10]
When you have a field which is an enum and request an invalid value, no error is given. Perhaps it's better to be strict, and slap the frontender with a nice theepot error message.

**Comment by sjamaan** [comment]
I've been wondering about this, but how would this work when you do, say, a `startswith` or a `contains` filter?  We could do it only for `in` or the identity filter, but I'm not sure that's very logical.

**Comment by mmoreaux** [comment]
@sjamaan would those filter qualifiers even make sense on enum fields?

**Comment by sjamaan** [comment]
I'm on the fence about that.  On one hand, an enum should have distinct values, but on the other hand, the enum is textual, and you **can** search on them in the DB.  If you group enums using a common prefix it might be useful to do that. But make much sense, it does not :)

Of course, it's also possible to use `choices` to restrict options in a non-enum way. You can even use `choices` on an integer field, I think. Would it make sense to be able to use `lt`/`gt` and such there?

**Comment by mmoreaux** [comment]
@sjamaan I suspect it's not often useful in practice, but I think we could limit the value-checking to exact match and `:in`.

> You can even use choices on an integer field, I think. Would it make sense to be able to use lt/gt and such there?

Maybe, yes.

**Comment by abzainuddin** [comment]
We've decided that this might not be worth fixing...
