### ISSUE TITLE
binder.json frozenset serializer

### ISSUE THREAD

**Issue by Daanvdk** [CodeYellowBV/django-binder#110]
Binder provides a default serializer for set (list) but not for frozenset in binder.json, seems incomplete.

**Comment by mmoreaux** [comment]
Well, Binder also doesn't provide serialization for `<map object>` or `Ellipsis` :P

Sane default serializers can be added as needed. If we actually have projects that try to serialize `frozenset`s, feel free to add a default serializer to Binder.

If this is hypothetical though, then please close the issue. The serializers will never cover every object you might encounter, and there's no point in trying. We should add what we actually use. :)

**Comment by sjamaan** [comment]
FWIW, I agree that we shouldn't include serializers for every single obscure object type that you might need once or twice. If it's a common enough type that it is (or is very likely to be) used in multiple projects I think it should be included.

**Comment by Daanvdk** [comment]
The thing with frozenset is that its the only one from the python builtins that we currently do not support, and the usage of set and frozenset is pretty interchangable in a lot of situations so supporting one but not the other can be a bit of a mindfuck when doing refactoring.

**Comment by mmoreaux** [comment]
> The thing with frozenset is that its the only one from the python builtins that we currently do not support

I don't think that's true; what about the examples I gave earlier, `map(id, [1,2,3])`, and `Ellipsis`?

> and the usage of set and frozenset is pretty interchangable

This is true, and I'm certainly not against adding support for it.

I'm taking a pragmatic view though; are we actually trying to serialize `frozenset`s in one or more projects?

**Comment by mmoreaux** [comment]
> For Ellipsis I do not think there is a logical thing to serialize too so that's a bit different as well.

Yeah, `Ellipsis` was a bit contrived, but it does illustrate my point about being complete for the sake of being complete.

> For current projects actually using it, in IB we had a view that used it where I manually converted it to lists but that view has been refactored and now doesn't use it anymore. But it is certainly possible to pop up some time again.

In that case I suggest adding `frozenset` support if and when that pops up again (and it's actually deemed desirable).

If it's useful, I'm all for adding it. But this ticket feels a bit like YAGNI ;)

**Comment by sjamaan** [comment]
This hasn't popped up again and I think we shouldn't try to kitchen-sink this. If necessary, please reopen, or just add project-specific support (for an example, see GIS `Point` class serialization in Boekestijn)
