### ISSUE TITLE
Should 'requests' be added to project/packages.pip?

### ISSUE THREAD

**Issue by noughtmare** [CodeYellowBV/django-binder#113]
When trying out the example project I encountered the error: 

> ModuleNotFoundError: No module named 'requests'

I fixed this by installing the requests package via pip manually, so should that be added to the packages.pip file?

**Comment by sjamaan** [comment]
It's [already there](https://github.com/CodeYellowBV/django-binder/blob/faster-and-virtual-withs/project/packages.pip#L5) in the `faster-and-virtual-withs` branch. This branch will be merged into `master` soonish.
