### ISSUE TITLE
Find out a good git workflow and document it

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/django-binder#12]
We need to find a good workflow with branches and releases. It is important that old major releases can still be maintained.

I am thinking about this workflow:

`master` is the 'development' branch. Work for the current stable release happens on here. For each major release (e.g. `v1`, `v2`), there will be a separate branch. When doing a minor or patch release, you can merge from `master` to the `v2` branch. If you want to also backport the fix to `v1`, you can cherry-pick from `master`. When you're done, you can tag a release.

**Comment by mmoreaux** [comment]
Sounds fine to me.

**Comment by shayneoneill** [comment]
Just use Git-flow. Its well understood, intuitive, and even comes with standard tooling in most distros, sourcetree, etc.

**Comment by sjamaan** [comment]
We've tried gitflow for internal projects and it didn't really provide us any benefits. For Binder, we just hack on `master`, for now we can coordinate things well enough.
