### ISSUE TITLE
Get rid of m2m_fields

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/django-binder#14]
When you ask for a related m2m field, Binder should automatically add this to the response. Example:

Without setting m2m_fields on order:

```
GET api/order/?with=products
{
   data: [{
       id: ..,
       // No product ids.
   }],
   with: {
       products: ...
   }
}
```

With setting m2m_fields = ['products'] on order:

```
GET api/order/?with=products
{
   data: [{
       id: ..,
       products: [1,2,3],
   }],
   with: {
       products: ...
   }
}
```

**Comment by sjamaan** [comment]
The whole `m2m_fields` list is redundant and should not be necessary.

**Comment by mmoreaux** [comment]
@sjamaan Not really, because returning fields as m2ms has a performance impact. That's why they're opt-in (at the view level).

If we make something so that the FE can request which (m2m) fields it wants to see, _then_ m2m_fields becomes redundant.

**Comment by sjamaan** [comment]
@mmoreaux We discussed this; The `with` indicates that the frontend is interested in this field.  If the `with` is present, show the data. Otherwise it can be omitted.

**Comment by mmoreaux** [comment]
That's not what I remember from the discussion, and I disagree; it's possible that the FE already has the referenced objects so it wants the m2ms but not as with. It's also possible that the FE wants to lazily load the related objects.

**Comment by mmoreaux** [comment]
For the record, what I remember from our discussion is that we'd like to have a mechanism where the FE can specify which fields (m2m or otherwise) it wants in the response, and we can deprecate `m2m_fields` in favour of this.

**Comment by abzainuddin** [comment]
Sometimes you also just need the length of the related fields, without getting the related objects. This could be solved by letting the FE decide which fields it wants.

**Comment by sjamaan** [comment]
@abzainuddin What do you mean by "length of the related fields"?  The number of items in the hasmany?

If so, this will be almost as expensive as fetching the entire related objects, because you'll still need another query (or a join) to get those records.

**Comment by sjamaan** [comment]
@abzainuddin What do you mean by "length of the related fields"?  The number of items in the hasmany?

If so, this will be almost as expensive as fetching the entire related objects, because you'll still need another query (or a join) to get those records.

**Comment by abzainuddin** [comment]
@sjamaan Yes, the number of items in the hasmany.

**Comment by mmoreaux** [comment]
@sjamaan roughly as expensive as getting `somem2m: [1,2,3,42]`, but lots cheaper than actually saying `with=somem2m`...

**Comment by mdamien** [comment]
:+1: for getting rid of `m2m_fields`

**Comment by SpaceK33z** [comment]
And another huge 👍 , I spent 3 hours last week debugging why the array with m2m thingies wasn't added :(.

**Comment by abzainuddin** [comment]
I too spend 2 hours down the rabbit hole in backbone-relation(-repository) to find where it went wrong. Missing m2m...

**Comment by mmoreaux** [comment]
So much hate for user error -grin-

**Comment by stefanmajoor** [comment]
I spend an hour today debugging this issue. Can you fix this?

**Comment by SpaceK33z** [comment]
I spent 2s today debugging this issue; remembered the vague frontend error as a result of this immediately and slapped the backender. 🥇

**Comment by sjamaan** [comment]
This should be a lot better now that `with` includes information about back references, so `m2m_fields` is no longer strictly necessary when you have `ForeignKey`s, and leaving it off improves performance immensely when you have lots of references to the model you're requesting.

In case of _actual_ `ManyToManyField`s I think `m2m_fields` is still required, but only if you really need to see the fields in the output. For a total fix, I think that should be taken care of as part of #84 (if we want to do that).

Current situation: good enough.
