### ISSUE TITLE
List available endpoints somewhere

### ISSUE THREAD

**Issue by mdamien** [CodeYellowBV/django-binder#21]
When using the wrong url, I get the `catch_all` error that just says the URI is invalid.

It would be nice to get the list of registered urls like a normal 404 with django.

This could lead to a more self-documenting API, just go to `api/`, it lists what you can access. (like DRF / Tastypie)

**Comment by sjamaan** [comment]
If we do this, I think it's best to only do this in debug mode. Or make an optional thing. In general, we don't want to encourage users to start relying on internal APIs.

**Comment by mmoreaux** [comment]
@damien we used to have that, but we took it out for some reason. I don't remember why, but maybe @abzainuddin does?

@sjamaan I agree that this should be a dev/debug thing.

**Comment by sjamaan** [comment]
Not important enough. The code in @mdamien's branch no longer works since the no-singleton-router changeset and changing it in a backwards-compatible way to support both methods is a little bit too ugly.
