### ISSUE TITLE
Make it easier to add custom fields to get_objs

### ISSUE THREAD

**Issue by sjamaan** [CodeYellowBV/django-binder#23]
When adding an `annotate`, it should not be necessary to copy/paste the `get_objs` definition or perform two queries.

**Comment by SpaceK33z** [comment]
Related to #2?

**Comment by sjamaan** [comment]
Probably, yes

**Comment by sjamaan** [comment]
Annotations are easier now and otherwise it's a duplicate of #2, so I'm closing this one.
