### ISSUE TITLE
Add support for OneToOneField

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/django-binder#25]
Currently Binder does not support OneToOneField. Please add support for this.

**Comment by abzainuddin** [comment]
POSTing of a model where the OneToOne is defined works, but posting the related model does not:

```
class Order
  ride=models.OneToOneField('ride.Ride', on_delete=models.CASCADE, related_name='order')

class Ride
```

Saving Order with a Ride works, saving a Ride with an Order does not...

**Comment by mmoreaux** [comment]
Can confirm; this works for GET and with, but not for PUT.

I made it work in branch one-to-one-save, but it needs tests.

**Comment by mmoreaux** [comment]
No one really knows what's up with this, but some code and tests are in master already. Merged the final commit.
