### ISSUE TITLE
Allow search in m2m fields

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/django-binder#4]
It's not possible to search in m2m fields (e.g. `api/foo?.user=1`).

**Comment by mmoreaux** [comment]
You can though, but you need to be explicit about filtering on the id: `api/foo?.users.id=1`

Maybe we could add support for doing `?.users=1` directly. Is it a good idea?

**Comment by SpaceK33z** [comment]
Oh, don't know why I forgot about that. Actually, in that case, I don't really care ;p.

**Comment by mmoreaux** [comment]
Maybe because it's undocumented, like so many other things :P
