### ISSUE TITLE
Removing foreign key doesn't update related model

### ISSUE THREAD

**Issue by abzainuddin** [CodeYellowBV/django-binder#40]
Schema: Dogs have (nullable) Owners.

When PUTting:

```
PUT api/owner/

{
   id: 1,
   dogs: [1, 2, 3]
}

```

It will link Dog 1, 2 and 3 to Owner 1. But 

```
PUT api/owner/

{
   id: 1,
   dogs: [1]
}

```

will not unlink Dog 2 and 3 from Owner 1.

**Comment by Daanvdk** [comment]
FIxed

**Comment by Daanvdk** [comment]
Apparently not fixed yet for when the dogs relation to owner is not nullable and dogs are soft deletable.

**Comment by sjamaan** [comment]
I believe this test is in error: it should validate that the objects have been deleted. Soft-deleted objects are included in a `.with` by default. I'll fix the test to validate that.
