### ISSUE TITLE
multi-put validation is short-circuited on first error

### ISSUE THREAD

**Issue by sjamaan** [CodeYellowBV/django-binder#43]
If you multi-put a main object plus a related object and the related object doesn't validate, Binder stops and reports the error on the related object.

It should continue and collect the validation errors of the main object, so the UI has an opportunity to show all the problems with a filled-in form rather than requiring a depth-first trial and error traversal through the tree of objects.

**Comment by Daanvdk** [comment]
ValidationErrors have an object property, in this case however it could thus be about multiple objects. What do you think would be the best way to handle that?

**Comment by sjamaan** [comment]
I'm not 100% sure about this (it's been a while since I looked into this), but I think the problem is that `deferred_m2ms` doesn't get populated when a validation error is raised (because it doesn't return normally)

**Comment by mmoreaux** [comment]
The current format is:
```
{
    "code": "ValidationError",
    "debug": {
        "request_id": "bf8e43ac-fffd-42f3-b0e8-923b24921edc"
    },
    "error": {
        "validation_errors": {
            "is7_identifier": [
                {
                    "code": "Platform with this Is7 identifier already exists."
                }
            ]
        }
    },
    "object": "Platform: asdfasdasdfasdf"
```
How shall we extend it to support multiple objects, and should we change the current format for PUT/POST?

**Comment by mmoreaux** [comment]
After discussion with @sjamaan @abzainuddin @SpaceK33z @Daanvdk we decided to completely overhaul this. It's shitty now so we might as well fix it properly.

New response format:
```
{
    "code": "ValidationError",
    "debug": {
        "request_id": "bf8e43ac-fffd-42f3-b0e8-923b24921edc"
    },
    "errors": {
        "platform": {
            "236": {
                "*": [{"code": "int_min", "message": "meeeeeeeeeh"}],
                "is7_identifier": [{ "code": "foo", "message": "foooooo"}],
                "name": [{ "code": "bar", "message": "baaaaaaar"}]
            }
        }
    }
}
```

We also might need parameters (e.g., a minimum number for minimum number validation errors). @Daanvdk will research this.

See also #62

**Comment by mmoreaux** [comment]
Refactor merged, closing.
