### ISSUE TITLE
`with` query parameter should accept array

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/django-binder#50]
At the moment you can do a request like `api/animal?with=breed,owner`. It uses comma's to separate relations. However this should be an array, or at least accept both. This would result in cleaner frontend code :).

**Comment by sjamaan** [comment]
There's no such thing as an "array" in the [URI spec](http://tools.ietf.org/html/rfc3986). This is a query parameter, not a JSON body. AFAIK Python (or rather, WSGI/Django) doesn't have the bogus notion that PHP does, where the presence of `[]` in the query key suddenly impact the representation of the query value (this actually has some security repercussions as well!).

However, repeating the same query param is allowed by the spec, so we could just say that if you want multiple withs, you have to do `api/animal?with=owner;with=breed`. The backend can just pick all those keys, which saves us some parsing as well. Changing the key name to `with[]` to "simulate" a PHP-like API is rather awkward, though.

**Comment by SpaceK33z** [comment]
> There's no such thing as an "array" in the URI spec.

<img src="http://s2.quickmeme.com/img/96/96a4320fc955f42cbbd250389f2b444983b3bf82e1ce15a263b84e36adbc7f3d.jpg" width="300" />

Okay, most JavaScript libraries use `with[]` as a default so that would have my preference, but it looks like it's possible to [change that default](https://github.com/ljharb/qs) (ctrl+f arrayFormat)

**Comment by sjamaan** [comment]
Repeating "with" will cause the URI to get longer with each thing you add, which can also result in problems regarding limits in browsers or servers. Using a single character to separate the items means you can add more withs without running into that limit (of course, this happens with other things too, like the `order_by` and so on)

So I'm not so convinced this is such a good idea, even if it allows us to have a bit less code on both sides. Especially given that a comma may not occur in field names anyway (if that **was** allowed, it would be rather broken, unless we can distinguish between percent-encoded and non-percent-encoded commas).

**Comment by mmoreaux** [comment]
I'm with @sjamaan on this one. The `?foo[]=` thing is a pretty sucky non-standard. I'm not a fan.

At the time, @abzainuddin and I actually decided to go for comma-separated lists only to get a clean, unambiguous API, and to minimize the URL length.

Bonus comment: what would happen on `?with=foo,bar&with[]=baz`?
