### ISSUE TITLE
nullable foreignKeys don't get unset properly

### ISSUE THREAD

**Issue by sjamaan** [CodeYellowBV/django-binder#51]
This is trivial to fix, but I'm making a ticket because this needs a test.

If you do a multi-put on an object, and remove an item from a reverse relation of a foreignkey, the id gets set to `null`, but the resulting object doesn't get saved, so when you fetch the main object again the related object is still there.

**Comment by mmoreaux** [comment]
This sounds like a duplicate of #40, can you verify?

**Comment by SpaceK33z** [comment]
Since #40 is fixed, this is probably also fixed

**Comment by sjamaan** [comment]
yeah, this was a duplicate
