### ISSUE TITLE
Make JSON serialization pluggable

### ISSUE THREAD

**Issue by sjamaan** [CodeYellowBV/django-binder#55]
For some projects, one might use exotic/nonstandard Django field types (think for example PostGIS types). We don't want to hardcode all those fields that we've used in one project or another (with all the dependency baggage that entails) in `jsondumps` and `jsonloads`.

Perhaps `BinderJsonEncoder` can provide a pluggable API, a bit like I did for filters in PR #36.

**Comment by mmoreaux** [comment]
I'm not sure I agree with _"We don't want to hardcode all those fields that we've used in one project or another (with all the dependency baggage that entails)"_. One of the nice things of binder is that we have the same API serialization everywhere. Having decent support for all that out of the box is a good thing I think.

The dependencies can be minimized by doing something like
```
try:
  import foo
  add "foo" support to JSON serialization
except ImportError:
  pass
```
That way you get the support _if_ you have the dependencies installed (which you will if the app needs them).

Not saying I disagree with making the serialization pluggable, but I don't quite agree with the premise. (I also heard something about timedelta for example, I really think support for that that should be built-in)

**Comment by sjamaan** [comment]
Dynamically importing stuff like that for some common classes is a good way to avoid dependency hell. But you'll eventually run into something that's so extremely application-specific that it doesn't fit in Binder. That was my point: we don't want to hardcode a field just because there is 1 project out of dozens that uses it.

In one project, for example, we have an `ExactOnlineCode` field that models a sort of id field in Exact Online.  It is just a subclass of `TextField` which is treated as an opaque handle, so in this particular case it doesn't matter, but if it did have structure, there's no point in including it in Binder.

Besides, checking all classes we've ever used in a project one by one is a linear search, for each and every element in a JSON document, and we do lots and lots of JSON serialization. That quickly becomes unwieldy.

**Comment by mmoreaux** [comment]
> But you'll eventually run into something that's so extremely application-specific that it doesn't fit in Binder.

I agree, and I tried to acknowledge that in my last paragraph.

> Besides, checking all classes we've ever used in a project one by one is a linear search, for each and every element in a JSON document, and we do lots and lots of JSON serialization. That quickly becomes unwieldy.

Are you talking about performance issues in the if/else chain in `jsondumps`?

**Comment by sjamaan** [comment]
> >  But you'll eventually run into something that's so extremely application-specific that it doesn't fit in Binder.
> I agree, and I tried to acknowledge that in my last paragraph.

Cool

> > Besides, checking all classes we've ever used in a project one by one is a linear search, for each and every element in a JSON document, and we do lots and lots of JSON serialization. That quickly becomes unwieldy.
> Are you talking about performance issues in the if/else chain in jsondumps?

yeah

**Comment by mmoreaux** [comment]
I suspect the impact on performance is fairly low. Anyway, an easy way to fix that is to use a `{class: lambda}` dict instead of the if/else tree, that gives us O(1) lookups. Also has the benefit of making it easier to add custom serialization types.

**Comment by JasperStam** [comment]
I need this for tms as well

**Comment by mmoreaux** [comment]
Done. `binder.json.BinderJSONEncoder` now uses a dictionary lookup on the value's class to determine the serializer method. It carries a lot of built-in ones, but you can add overrides using `settings.BINDER_JSON_SERIALIZERS`.

Add something like this to `settings.py`:

```python
def serializer_foo(encoder, value):
    return value.someformat()

BINDER_JSON_SERIALIZERS = {Foo: serializer_foo}
```

A lambda would work too. (`{Foo: lambda e, v: v.format()})

**Comment by mmoreaux** [comment]
Beware! Refactored, interface changed.

Now do `binder.json.SERIALIZERS.update({})` from `settings.py`.
