### ISSUE TITLE
Multi-PUT; Binder expects relations to be specified from the object with the FK

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/django-binder#57]
Given this request body in a multi-PUT relation;

```js
{
  data: { // <-- this model is called "ride"
    id: -1,
    activities: [-2]
  },
  with: {
    activity: [{
      id: -2,
    }]
  }
}
```

Binder will error here with something like this:

```
{ "object": "Activity: Activity object", "code": "ValidationError", "error": {"validation_errors": {"ride": [{"code": "This field cannot be null."}]}
```

This is because Binder expects you to also set the id of the `ride` model on the `activity` model. So this request will work:

```js
{
  data: {
    id: -1,
    activities: [-2]
  },
  with: {
    activity: [{
      id: -2,
      ride: -1, // <-- added backref
    }]
  }
}
```

This backref should not be necessary and makes it harder for us frontend boys 🤠 .

Related ticket in mobx-spine; https://github.com/CodeYellowBV/mobx-spine/issues/28

**Comment by mmoreaux** [comment]
Binder doesn't need it both ways, just from the object that actually has the FK; the reference the other way (from the object the FK points to) is optional.

And, from the perspective of the DB, this `ride: -1` is actually the _forward_ ref ;)

Still, definitely worth fixing. I feel Binder should be satisfied when you specify _either_. Or both.

**Comment by Daanvdk** [comment]
Done in commit 3ee269d0e14eede6b379494a1d3cd3680d6f6bf0
