### ISSUE TITLE
Multi-PUT; support nested field validation errors

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/django-binder#59]
In TMS you have an `Order` model which has a one-to-many on `Activity`. The `Activity` has a field `house_number`, which is required. When performing a multi-PUT on the `Order`, without any data, you get this:

```json
{
  "error": {
    "validation_errors": {
      "house_number": [
        {
          "code": "This field cannot be null."
        }
      ]
    }
  },
  "code": "ValidationError"
}
```

You can see here that the `house_number` is not scoped to the activity. I would expect it to return something like this:

```json
{
  "error": {
    "validation_errors": {
      "activities[0].house_number": [
        {
          "code": "This field cannot be null."
        }
      ]
    }
  },
  "code": "ValidationError"
}
```

That way the frontend can map it precisely to a specific activity. Note that we also did it like this in our old PHP stack.

**Comment by mmoreaux** [comment]
Fixed in validation refactor, closing.
