### ISSUE TITLE
Validation errors should return an actual code, not a message

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/django-binder#62]
```js
{
  "error": {
    "validation_errors": {
      "house_number": [
        {
          "code": "This field cannot be null."
        }
      ]
    }
  },
  "code": "ValidationError"
}
```

The field `code` in `house_number` says "This field cannot be null". But this is a message, not a code. The problem with this is that we have translations in the frontend, but we can't easily map that if such a message is used instead of a code. So we want to do the code -> message stuff completely in the frontend, where the translations live.

Note that perhaps some validation messages have dynamic values in them (something like "Field can be max `<integer>` characters long." Such values can be added to the same object where `code` lives in.

**Comment by mmoreaux** [comment]
@SpaceK33z This has seen work during the validation refactor; is the current solution satisfactory, and can we close this?
