### ISSUE TITLE
Django full_clean() vs Binder null-check mess

### ISSUE THREAD

**Issue by mmoreaux** [CodeYellowBV/django-binder#66]
This is getting uglier by the minute...

The initial problem:

We have `FooModel.barfield = CharField(max_length=42, blank=True)`.
We `POST /api/foo_model/  {}`. No problemo.
We `POST /api/foo_model/  {"barfield": null}`. Kaboom, 500.

Why? Because Django's `full_clean()` sees `blank=True` and decides `None` is appropriate, not raising a ValidationError. Later, on `save()`, Django passes `NULL` to Postgres, which raises a constraint error.

This behaviour seems at least semi-deliberate, see the comment in the middle of `django/db/models/base.py:1251:clean_fields()`:

```python
def clean_fields(self, exclude=None):
    """ 
    Cleans all fields and raises a ValidationError containing a dict
    of all validation errors if any occur.
    """ 
    if exclude is None:
        exclude = []

    errors = {}
    for f in self._meta.fields:
        if f.name in exclude:
            continue
        # Skip validation for empty fields with blank=True. The developer
        # is responsible for making sure they have a valid value.
        raw_value = getattr(self, f.attname)
        if f.blank and raw_value in f.empty_values:
            continue
        try:
            setattr(self, f.attname, f.clean(raw_value, self))
        except ValidationError as e:
            errors[f.name] = e.error_list

    if errors:
        raise ValidationError(errors)
```
The fix for this _was_:

```python
# full_clean() doesn't check nullability (WHY?), so do it here. See T2989.
for f in obj._meta.fields:
    # Ok, this nullable check poses problems. For example, when using MPTT models, we subclass
    # the MPTTModel, which defines not-NULL bookkeeping fields which it populates on save().
    # However, for new objects, this check occurs *before* the super().save(), so it complains.
    # See T9646. Current solution: these fields are strictly populated by the backend, so
    # they're unwritable from the frontend. So, unwritable -> no NULL check.  ¯\_(ツ)_/¯
    if f.name in self.unwritable_fields:
        continue
    name = f.name + ('_id' if isinstance(f, models.ForeignKey) or isinstance(f, models.OneToOneField) else '') 
    if not f.primary_key and not f.null and getattr(obj, name) is None:
        validation_errors[f.name] = ['This field cannot be null.'] 
```

Which worked OK for a while. But after @Daanvdk's validation refactor, the modified version was throwing double validation errors for some fields. We needed something a little stricter. So it became:

```python
# full_clean() doesn't complain when CharField(blank=True, null=False) = None
# This causes save() to explode with a django.db.IntegrityError because the
# column is NOT NULL. Tyvm, Django.
# So we check this case here.
for f in obj._meta.fields:
    # Primary keys are a bit special, they're NOT NULL, but .save() populates them.
    # So we ignore primary keys.
    if (f.blank and not f.null) and not f.primary_key:
        # gettattr on a foreignkey foo gets the related model, while foo_id just gets the id.
        # We don't need or want the model (nor the DB query), we'll take the id thankyouverymuch.
        name = f.name + ('_id' if isinstance(f, models.ForeignKey) else '')

        if getattr(obj, name) is None:
            e = BinderValidationError({
                self._model_name(): {
                    obj.pk if pk is None else pk: {
                        f.name: [{
                            'code': 'null',
                            'message': 'This field cannot be null.'
                        }]
                    }
                }
            })
            validation_errors.append(e)
```

No more check for `unwritable_fields`, but now it does check explicitly for `blank`. Of course, this doesn't work, for example for `DateTimeField(auto_now_add=True)`. So @JasperStam changed it to:

```python
# full_clean() doesn't complain when CharField(blank=True, null=False) = None
# This causes save() to explode with a django.db.IntegrityError because the
# column is NOT NULL. Tyvm, Django.
# So we check this case here.
for f in obj._meta.fields:
    if (f.blank and not f.null) and not is_filled_upon_save(f):
        # gettattr on a foreignkey foo gets the related model, while foo_id just gets the id.
        # We don't need or want the model (nor the DB query), we'll take the id thankyouverymuch.
        name = f.name + ('_id' if isinstance(f, models.ForeignKey) else '')

        if getattr(obj, name) is None:
            e = BinderValidationError({
                self._model_name(): {
                    obj.pk if pk is None else pk: {
                        f.name: [{
                            'code': 'null',
                            'message': 'This field cannot be null.'
                        }]
                    }
                }
            })
            validation_errors.append(e)
```

This is quickly getting out of hand; none of this fixes the actual problem, and exceptions to whatever rule we conceive keep popping up. How to fix this properly?

I see a few options:

 - Remove the check altogether. This means we get 500s when the frontend does `POST {"barfield": null}`, which I don't like. It also means not specifying a field like `DateTimeField(blank=True)` 500s, but that arguably is a back-end programming error anyway...
 - Omit the check for fields in `unwritable_fields` like we used to do. Stuff like MPTT fields or `updated_at`, which get populated in `save()` should be unwritable and this way won't trigger the problem. But does this cover all cases? What if you want a `DateTimeField(auto_add_now=True)` that _also_ can be set from the FE?
 - Only perform this additional null-check when the field is actually present in the request body. So auto-populated stuff that is `unwritable_fields` never triggers this. But what if you have a `DateTimeField(auto_add_now=True)` and the FE passes in `null` to have the BE use `NOW()` in the `UPDATE`? Still a fake error...
 - Complain to Django that their `full_clean()` behaviour is problematic. I'm not sure how successful this is going to be, as the behaviour seems semi-intentional, but it might be worth trying anyway.

**Comment by mmoreaux** [comment]
Another option: limit the check to field types known to be problematic, such as `CharField` and `TextField`...

**Comment by JasperStam** [comment]
> Another option: limit the check to field types known to be problematic, such as CharField and TextField...

This is my preference. Currently the view makes assumptions about which fields are going to fail the nullable field constraint, before saving the actual model.

The result is that any logic done in the `model.save` gets ignored, because of incorrect assumptions in the view.

This would be my preferred solution in pseudocode:
```
class BinderModel:
  def full_clean:
     super().full_clean
     check for not nullable field violations (which occurs in blank=True fields)
```

**Comment by JasperStam** [comment]
Hmm I just realized we do a full_clean check before the save anyways, so model.save logic is ignored anyway. It doesn't change my preferred solution though.

**Comment by sjamaan** [comment]
I just ran into an issue with the current implementation:

In a project, I have a custom `AutoDateTimeField` field class. These fields are automatically filled in whenever another field is filled in for the first time (so you know when it was first set). In this sense it behaves a lot like auto_now=True in `DateTimeField`, but with a conditional value of `auto_now`. 

These fields are unwritable, and usually (in almost all cases) they're nullable, because they should get set only when their corresponding fields are set. However, in one situation it's not nullable, because the corresponding other field is always required. This causes Binder to complain that the field is empty, but it will handle this itself.  So, using a hardcoded list of built in field classes that may be empty is too limited. Of course, in my particular situation, a simple fix is to add `auto_now_add=True` because the matching field will always be set on creation. But still, it would be nice if there were some way to change the predicate.

**Comment by mmoreaux** [comment]
I'm starting to wonder if we should simply not check for it, and catch/parse any resulting `DBIntegrityError`. It involves parsing the exception, which sucks, but it would be fool-proof wrt. anything `save()` may or may not do.

**Comment by sjamaan** [comment]
That sounds even worse, TBH

**Comment by SpaceK33z** [comment]
> I'm starting to wonder if we should simply not check for it, and catch/parse any resulting DBIntegrityError.

Isn't that tricky because Django doesn't always create the most strict columns possible? E.g. fake enums that are not enforced on database-level. Ignore me if I'm wrong, I'm just a pauper frontender

**Comment by mmoreaux** [comment]
Ah, to clarify: I meant catching DBIntegrityError _just for the NULL check issue_. That's the part we're having trouble with, and it's something that Postgres will catch reliably.

**Comment by SpaceK33z** [comment]
Allright. Another question: Postgres will throw immediately when the first NULL check fails for a field fails, right? Since we show *all* validation errors to the frontend at once (not one error for one field at a time), wouldn't you need to trigger a save for each field?

**Comment by mmoreaux** [comment]
Fair point, and it was an ugly hack to begin with... Back to the mess we already had I guess.

**Comment by mmoreaux** [comment]
@sjamaan and I had a look at this, we decided to completely turn this around.

The problem is that in some cases, `full_clean()` doesn't check for null/None, and this causes an exception in `save()`. So we make explicit checks for these cases, rather than a more generic check with gnarly exceptions.

See `ModelView.field_needs_nullability_check()`.

**Comment by mmoreaux** [comment]
So this is gonna be The New Solution (tm).

If there are other field types for which this problem arises, they can be added in Binder to `ModelView.field_needs_nullability_check()`.

If there are app/model specific cases where this needs to be checked, `field_needs_nullability_check()` can be overridden for the relevant View.

**Comment by sjamaan** [comment]
This works well enough for me. I've never run into this problem since, and overriding for specific fields should do the trick when necessary.
