### ISSUE TITLE
History contains redundant data, ballooning the DB

### ISSUE THREAD

**Issue by mmoreaux** [CodeYellowBV/django-binder#76]
Binder's history can get quite big, and some of the data is redundant. We should consider pruning this.

For example, when a FK changes, Binder also records the reverse of that in the DB. In AAA-Lux, a Product has an FK `packager` to Operator. So when an Operator packages a Product, Binder's history records

 - `Product(1).packager`: `null` -> `1`
 - `Packager(1).packaged_products`: `[]` -> `[1]`

This second line is redundant (but can be nice to have). And eh, what's the harm? Then the operator packages another product:

 - `Product(2).packager`: `null` -> `1`
 - `Packager(1).packaged_products`: `[1]` -> `[1, 2]`

His 20th product:

 - `Product(20).packager`: `null` -> `1`
 - `Packager(1).packaged_products`: `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]` -> `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]`

Well, shit.

AAA-Lux compressed DB dumps are about 200MB right now. After simply dropping those reverse FK histories (which are redundant!) that size falls to 11MB.

I want to stop recording those reverse FK lists in history, and prune them from existing histories.

### More redundancy: object creation

When an object is created, all its fields end up in history with `null` -> `<initial value>`. But that value is on the actual object itself, the value in the history is redundant! Removing those values dropped the AAA-Lux DB from 11M to 4M. We should consider not recording all those values on object creation.

### Even more redundancy: before/after

Every history change records the value before _and after_ the change. This is redundant, one would suffice (which of the two depends partly on the other issues above). Stripping this didn't seem to make a huge difference for AAA-Lux though.

Thoughts?

**Comment by mmoreaux** [comment]
Alright, this is done and can be tested! Use the `history-no-reverse-fk` branch to test.

**Comment by sjamaan** [comment]
This has been in production for a while, and it works.  If this is not sufficient, I think a new ticket should be made.

**Comment by mmoreaux** [comment]
@sjamaan Is the `history-no-reverse-fk` branch still used anywhere or can we kill it?
