### ISSUE TITLE
Virtual relations

### ISSUE THREAD

**Issue by stam** [CodeYellowBV/django-binder#80]
We have a certain project where relations are based on date.

An allocation has a set of assignments, each assignment has a start_date and end_date. This construction gives us a virtual relation `allocation.current_assignment` which is the assignment which is valid for today.

We could solve this by a database foreign key, but this requires a lot of bookkeeping: manually setting the right assignment for that date, and recalculating everything when something date related has changed.

Another way to solve this is by virtual relations. This requires a `shown_property` for the computed foreign key on the model, and a hack in the `_get_with` of the view. 

I would like to see something like this:
```python
@virtual_relation(model=Assignment, name='current_assignment', singular=True)
def current_assignment(self):
    q = Q(end_date__isnull=True) | Q(end_date__gte=timezone.localdate())
    return self.assignments.filter(q).order_by('start_date')
```

Which generates a (shown_) property for the model which lists the id and allows the relation to be `with`able

**Comment by sjamaan** [comment]
We sort of have had this for a while now. It's a bit shitty but it seems to work.
