### ISSUE TITLE
Allow filtering in ArrayField field

### ISSUE THREAD

**Issue by SpaceK33z** [CodeYellowBV/django-binder#85]
Currently, filtering on an `ArrayField` through the api, `api/animal?.favorite_foods:in=milk` returns a 418 response with `Filtering not supported for type ArrayField ({Animal}.{favorite_foods}).`

I'd expect that it is possible to use the `:in` and `:not:in` qualifiers for arrays.

**Comment by sjamaan** [comment]
I agree it should be possible to filter in arrays, but filtering with `in` makes no sense: the array is what contains multiple values, while normally with `in` it's the values list (separated by commas) which has multiple values (example: `id:in=1,2,3`).

This should be properly considered, and the operator set should be based on [what Django's Postgres API supports](https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#querying-arrayfield). While we're at it, a similar API should also work for JSON fields.

**Comment by mmoreaux** [comment]
We could expose those django operators, yes. That would probably be the simplest and least surprising way to do it.

**Comment by mmoreaux** [comment]
Note that this is already how we do many filter operations (`:startswith` etc).

**Comment by sjamaan** [comment]
@mmoreaux I started work on this but got stranded pretty soon. To make this work I'd appreciate if you could merge #36 as that makes parse_filter more reusable: this will make it possible to process the values of the sub-field inside the array (and make support for nested array fields easier/possible too)

**Comment by mmoreaux** [comment]
Merged, go nuts.
