### ISSUE TITLE
Add helper method to initiate other router

### ISSUE THREAD

**Issue by stefanmajoor** [CodeYellowBV/django-binder#86]
So a pattern that I see occurring way to often is the following:

```
class FooView:
   def bar(self):
         baz_view = BazView()
         baz_view.router = self.router
```

I believe that this is bad, since binder logic leaks into the actual views. Furthermore, every time the way a view is created is changed, all these calls need to be replaced. This is especially hard because the resulting errors may or may not occur, and most of the time somewhere unrelated. Therefore I propose adding a sensible way to do this. 

I propose either of the following interfaces:
```
class FooView:
   def bar(self):
         baz_view = self.get_view(BazView)
```

Or
```
class FooView:
   def bar(self):
         baz_view = self.router.get_view(BazView)
```

**Comment by mmoreaux** [comment]
Alright, I added `BinderView().get_view()` and `BinderView().get_model_view()`.
