### ISSUE TITLE
unwritable_fields are writable if you add a _store_fieldname function

### ISSUE THREAD

**Issue by stefanmajoor** [CodeYellowBV/django-binder#88]
If you add a `_store_foo` in the `UserView`, then the `_store_field` is not called, and the field is writable again if the `_store_foo` doesn't call the `_store_field_` explicitely. Although technically not a bug itself, it is not obvious and results in unexpected bahavior.

**Comment by mmoreaux** [comment]
> "Although technically not a bug itself"
>
> stefanmajoor added the bug label

¯\_(ツ)_/¯

How do you think this should behave then?

**Comment by stefanmajoor** [comment]
I think the behavior is wrong.  Although it is intended like this, this behavior is unexpedcted

What should be the case is, if the field 'foo' is set as read only,  _store_foo shouldn't be called, ever.  Otherwise you have a read only field, which you can actually write too. Which is odd.

**Comment by mmoreaux** [comment]
I don't agree. The writability check is done in `_store_foo`. If you override that, it's your own responsibility to respect that. What else is even the point of `_store_foo`, if it's never called?

Also, fields like `id` and `deleted` are implicitly in `unrwritable_fields`; changing this behaviour would make it impossible to make `_store_` methods for them.

**Comment by stefanmajoor** [comment]
> I don't agree. The writability check is done in _store_foo. If you override that, it's your own responsibility to respect that
Ok, it was not entirely clear to me that _store_foo overrides _store_field.

>  What else is even the point of _store_foo, if it's never called?
Nothing. _store_foo shouldn't exist. But that doesn't mean that it might not be there (because somebody copy-pasted something). I believe it is very strange that something is set as unwritable, but can still be written too.

> Also, fields like id and deleted are implicitly in unwritable_fields; changing this behaviour would make it impossible to make _store_ methods for them.

The second part is technically untrue, of course you can create a _store_ method, but it won't be called. You want the ability to change the default unwritable fields. These are hard coded at the moment.  Bad implementation shouldn't be an argument for design decisions.

I believe that can make for nasty bugs, and potentially security violations, because implementing _store_FOO for an unwritable field FOO makes it writable. I believe that such a case would happens more on accident, then it happens intentionally.

**Comment by mmoreaux** [comment]
The simple fact is that `_store` only delegates writes to their respective `_store__foo` methods with `_store_field` as fallback. If you define `_store_foo`, you're also responsible for such checks. That doesn't just include writability, but also type checking and validation.

I do see your point, and it's not ideal design; but I do believe there's a consistency about how this works, and I feel the effort and potential breakage involved in changing this aren't worth it currently.

**Comment by stefanmajoor** [comment]
I believe that this still is not completely the way it should be. 

But as least I/we are aware that this is happening right now. The documentation updates make it clearer what is happening. At this moment I believe that changing the behavior is not worth the size of the change that is necessary for this.
