### ISSUE TITLE
Warning on CaseInsensitiveCharField

### ISSUE THREAD

**Issue by Daanvdk** [CodeYellowBV/django-binder#92]
`CaseInsensitiveCharField` gives a warning when instantiated, this seems fine but this is also triggered when running old migrations. This gave me a few 100 lines of warnings when running tests for a project since it was creating the test database. Temp fixed for now by changing the old migrations to use `django.contrib.postgres.fields.CITextField` instead since that behaves exactly the same anyway but having to change old migrations always feels like a stupid hack.

**Comment by sjamaan** [comment]
That's exactly the correct thing to do. Django offers no nice way to remove field types from your source code without upsetting the migrations, I'm afraid.
