### ISSUE TITLE
Filtering on property

### ISSUE THREAD

**Issue by Daanvdk** [CodeYellowBV/django-binder#93]
On a view you can add property names to `shown_properties` to include them in the returned values for an instance. However it is currently impossible to filter on those values, I get that this can't be done in a query and thus might be tricky or very inefficient to do.

Any ideas on this?

**Comment by mmoreaux** [comment]
I'd say you have to provide a custom filter method for it as well.

E.g. (quick draft from the top of my head, for inspiration only):

```
class FooView:
    shown_properties = ['bar']

    def bar(self, ...):
        ...

    def bar_filter(self, value, queryset, request):
        return queryset.filter(qux=warple(value))
```

Then you can do all the necessary crazy shit in `bar_filter`.

**Comment by sjamaan** [comment]
This is now superseded by annotations.
