### ISSUE TITLE
Add validation that inner classes on Binder models inherit from BinderModel's inner class

### ISSUE THREAD

**Issue by sjamaan** [CodeYellowBV/django-binder#96]
Apparently (and this was new to me, but in hindsight it makes perfect sense), when you define a `Meta` class inside a class which inherits from `BinderModel`, it clobbers the defaults from `BinderModel.Meta`.

We might want to add a check that when you inherit from `BinderModel`, that any `Meta` (and other inner classes?) actually inherit from `BinderModel.Meta`.

**Comment by mmoreaux** [comment]
This is surprisingly hairy.

Django's `Modelbase.__new__()` removes `Foo.Meta`, messes around with it, and replaces it with the super abstract Meta. Or something.

The end result is:
```
SalesOrder(BinderModel):
    Meta:
        pass

issubclass(SalesOrder.Meta, BinderModel.Meta) == True
```
wtf

But the actual values are not used on `SalesOrder.Meta`, but on `SalesOrder()._meta`, which is an "Options" object, which does not inherit `BinderModel.Meta`s properties. Ugh.
